import {useCallback,useEffect,useMemo,useState} from 'react';
import {ArrowRight,CalendarDays,Circle,Eclipse,ChevronLeft,ChevronRight,Clock,Download,ExternalLink,FlaskConical,GraduationCap,LayoutGrid,ListOrdered,LogOut,MapPin,Monitor,Moon,Plus,RefreshCw,Settings2,ShieldCheck,Sun,UserRound,Users} from 'lucide-react';
import {api,setCsrf} from './api';
import {nextTheme,parseTheme,resolveTheme} from './theme';
import {copy,errorText,roleLabel} from './i18n';
import {addDays,addMonths,dateInZone,format,fromIso,iso,monday,monthGrid,parity} from './date';
import type {Lang,Lesson,QueueSummary,Settings,Theme,User} from './types';
import {AppContext,Badge,Button,Dialog,Empty,Field,IconButton,Loading,Notice,Toast,useApp,useJob,useT} from './ui';
import Auth,{type Session} from './Auth';
import Admin from './Admin';
import LessonForm from './LessonForm';
import QueuePanel from './QueuePanel';

const defaults:Settings={group:'БВТ2302',program:'09.03.01',course:4,semester_start:'2026-09-01',semester_end:'2027-01-31',anchor_monday:'2026-08-31',anchor_parity:'odd',timezone:'Europe/Moscow',revision:1,configured:false};
function preference(key:string,fallback:string){try{return localStorage.getItem(key)||fallback;}catch{return fallback;}}
function savePreference(key:string,value:string){try{localStorage.setItem(key,value);}catch{/* Device preferences are optional. */}}
function route(){const value=location.hash.slice(1);return ['calendar','queues','admin','preferences'].includes(value)?value:'schedule';}

export default function App(){
 const [lang,setLang]=useState<Lang>(preference('cf-language','ru')==='en'?'en':'ru');
 const [theme,setTheme]=useState<Theme>(()=>parseTheme(preference('cf-theme','system')));
 const [user,setUser]=useState<User|null>(null);const [settings,setSettings]=useState(defaults);const [revision,setRevision]=useState(0);const [ready,setReady]=useState(false);const [setup,setSetup]=useState(false);const [error,setError]=useState('');const [toast,setToast]=useState<{message:string;error:boolean}|null>(null);const [page,setPage]=useState(route);
 const refresh=useCallback(()=>setRevision(v=>v+1),[]);const notify=useCallback((message:string,error=false)=>setToast({message,error}),[]);const closeToast=useCallback(()=>setToast(null),[]);
 const onSession=useCallback((s:Session)=>{setCsrf(s.csrf);setUser(s.user);setSetup(false);refresh();},[refresh]);
 useEffect(()=>{document.documentElement.lang=lang;savePreference('cf-language',lang);},[lang]);
 useEffect(()=>{savePreference('cf-theme',theme);const m=matchMedia('(prefers-color-scheme: dark)');const apply=()=>document.documentElement.dataset.theme=resolveTheme(theme,m.matches);apply();m.addEventListener('change',apply);return()=>m.removeEventListener('change',apply);},[theme]);
 useEffect(()=>{const listener=()=>setPage(route());window.addEventListener('hashchange',listener);return()=>window.removeEventListener('hashchange',listener);},[]);
 useEffect(()=>{let active=true;async function load(){try{const status=await api<{needs_setup:boolean}>('/api/auth/status');if(!active)return;setSetup(status.needs_setup);let session:Session|null=null;try{session=await api<Session>('/api/auth/me');}catch(e){if(!['unauthorized','account_inactive'].includes((e as {code:string}).code))throw e;}if(!active)return;setCsrf(session?.csrf||'');setUser(session?.user||null);if(session){const s=await api<Settings>('/api/schedule/settings');if(active)setSettings(s);}if(active)setError('');}catch(e){if(active)setError(errorText(lang,e));}finally{if(active)setReady(true);}}void load();return()=>{active=false;};},[revision,lang]);
 const context=useMemo(()=>({lang,setLang,theme,setTheme,user:user!,settings,refresh,notify}),[lang,theme,user,settings,refresh,notify]);
 async function logout(){try{await api('/api/auth/logout','POST',{});setUser(null);setCsrf('');location.hash='schedule';}catch(e){notify(errorText(lang,e),true);}}
 return <AppContext.Provider value={context}>{!ready?<Loading/>:error&&!user?<div className="standalone-error"><Notice error>{error}</Notice><Button onClick={refresh}>{lang==='ru'?'Повторить':'Retry'}</Button></div>:!user?<Auth key={String(setup)} setup={setup} onSession={onSession}/>:<div className="app-shell"><a className="skip-link" href="#main">{copy[lang].skipLink}</a><Sidebar page={page} onLogout={logout}/><div className="workspace"><header className="topbar"><div className="workspace-label"><GraduationCap size={19}/><span>МТУСИ</span><span className="top-divider"/>{settings.group}<Badge>{tCourse(lang,settings.course)}</Badge></div><div className="topbar-actions"><button className="language-button" onClick={()=>setLang(lang==='ru'?'en':'ru')} aria-label={copy[lang].language}>{lang.toUpperCase()}</button><IconButton label={copy[lang].appearance+': '+copy[lang][theme]} onClick={()=>setTheme(nextTheme(theme))}>{theme==='system'?<Monitor size={19}/>:theme==='dark'?<Moon size={19}/>:theme==='black'?<Eclipse size={19}/>:theme==='ultra-black'?<Circle size={19}/>:<Sun size={19}/>}</IconButton><div className="avatar small" title={user.name}>{initials(user.name)}</div></div></header><main id="main" tabIndex={-1} className="main-content">{error&&<Notice error>{error}<button onClick={refresh}>{copy[lang].retry}</button></Notice>}{page==='admin'&&user.role!=='student'?<Admin revision={revision}/>:page==='preferences'?<Preferences onSession={onSession}/>:page==='queues'?<Queues revision={revision}/>:<Schedule calendar={page==='calendar'} revision={revision}/>}</main><footer className="app-footer"><span>{copy[lang].notOfficial}</span><span>{settings.timezone} · v1.0.0</span></footer></div></div>}{toast&&<Toast {...toast} onClose={closeToast}/>}</AppContext.Provider>;
}
function tCourse(lang:Lang,n:number){return lang==='ru'?n+' курс':'Year '+n;}
function initials(name:string){return name.split(' ').map(s=>s[0]).slice(0,2).join('');}
function Sidebar({page,onLogout}:{page:string;onLogout:()=>void}){const t=useT();const {user,lang,settings}=useApp();const nav=[{id:'schedule',Icon:LayoutGrid},{id:'calendar',Icon:CalendarDays},{id:'queues',Icon:ListOrdered},...(user.role==='student'?[]:[{id:'admin',Icon:ShieldCheck}]),{id:'preferences',Icon:Settings2}];return <aside className="sidebar"><a className="brand" href="#schedule"><span className="brand-mark"><CalendarDays size={24}/></span><span>campus<span className="brand-light">flow</span><small>{settings.group}</small></span></a><p className="nav-label">{t('workspace')}</p><nav aria-label={t('navigation')}>{nav.map(({id,Icon})=><a key={id} aria-label={t(id)} href={'#'+id} className={page===id?'active':''} aria-current={page===id?'page':undefined}><Icon size={20}/><span>{t(id)}</span>{page===id&&<span className="nav-active-mark"/>}</a>)}</nav><div className="sidebar-bottom"><div className="semester-rail"><span>{t('semester')}</span><strong>{format(fromIso(settings.semester_start),lang,{month:'short',year:'numeric'})}</strong><small>{t('to')} {format(fromIso(settings.semester_end),lang,{day:'numeric',month:'short'})}</small></div><div className="sidebar-user"><div className="avatar">{initials(user.name)}</div><div><strong>{user.name}</strong><small>{roleLabel(lang,user.role)}</small></div><IconButton label={t('logout')} onClick={onLogout}><LogOut size={18}/></IconButton></div></div></aside>;}

function Schedule({calendar,revision}:{calendar:boolean;revision:number}){
 const t=useT();const {settings,lang,user,refresh}=useApp();const manage=user.role!=='student';const [date,setDate]=useState(()=>dateInZone(settings.timezone));const [subgroup,setSubgroup]=useState(0);const [kind,setKind]=useState('all');const [lessons,setLessons]=useState<Lesson[]>([]);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<Lesson|null>(null);const [adding,setAdding]=useState(false);const [reload,setReload]=useState(0);
 const grid=calendar?monthGrid(date):Array.from({length:7},(_,i)=>addDays(monday(date),i));const start=iso(grid[0]);const end=iso(grid[grid.length-1]);
 useEffect(()=>{let active=true;let busy=false;setLoading(true);setLessons([]);async function load(){if(busy)return;busy=true;try{const items=await api<Lesson[]>('/api/schedule/occurrences?start='+start+'&end='+end+'&subgroup='+subgroup);if(active){setLessons(items.sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)));setError('');}}catch(e){if(active)setError(errorText(lang,e));}finally{busy=false;if(active)setLoading(false);}}void load();const id=setInterval(()=>{if(!document.hidden)void load();},15000);return()=>{active=false;clearInterval(id);};},[start,end,subgroup,revision,reload,lang]);
 const filtered=lessons.filter(l=>kind==='all'||l.kind===kind);const today=iso(dateInZone(settings.timezone));const activeLessons=filtered.filter(l=>l.status!=='cancelled');const outside=end<settings.semester_start||start>settings.semester_end;
 return <><div className="page-heading"><div><span className="eyebrow">{settings.group} / {settings.program}</span><h1>{t(calendar?'calendar':'schedule')}</h1><p>{calendar?format(date,lang,{month:'long',year:'numeric'}):format(fromIso(start),lang,{day:'numeric',month:'long'})+' — '+format(fromIso(end),lang,{day:'numeric',month:'long',year:'numeric'})}</p></div><div className="heading-actions"><a className="button secondary" title={t('exportHint')} href={'/api/schedule/calendar.ics?start='+start+'&end='+end+'&lang='+lang+'&subgroup='+subgroup}><Download size={17}/><span>{t('export')}</span></a>{manage&&<Button onClick={()=>setAdding(true)}><Plus size={18}/>{t('addLesson')}</Button>}</div></div>
 {!settings.configured&&<Notice>{t('needsCalendar')} {manage&&<a href="#admin">{t('setupSchedule')}</a>}</Notice>}
 {lessons.some(l=>l.demo)&&<div className="demo-banner"><Badge tone="amber">{t('demo')}</Badge>{t('demoWarning')}</div>}
 <section className="schedule-board"><div className="schedule-toolbar"><div className="date-navigation"><IconButton label={t('prev')} onClick={()=>setDate(calendar?addMonths(date,-1):addDays(date,-7))}><ChevronLeft size={20}/></IconButton><Button variant="secondary" onClick={()=>setDate(dateInZone(settings.timezone))}>{t('today')}</Button><IconButton label={t('next')} onClick={()=>setDate(calendar?addMonths(date,1):addDays(date,7))}><ChevronRight size={20}/></IconButton><input aria-label={t('date')} type="date" value={iso(date)} onChange={e=>e.target.value&&setDate(fromIso(e.target.value))}/></div><div className="schedule-filters"><select aria-label={t('subgroup')} value={subgroup} onChange={e=>setSubgroup(+e.target.value)}><option value={0}>{t('allGroups')}</option><option value={1}>{t('subgroup')} 1</option><option value={2}>{t('subgroup')} 2</option></select><select aria-label={t('kind')} value={kind} onChange={e=>setKind(e.target.value)}>{['all','lecture','lab','practice'].map(k=><option key={k} value={k}>{t(k)}</option>)}</select><IconButton label={t('refresh')} onClick={()=>setReload(v=>v+1)}><RefreshCw size={18}/></IconButton></div></div>
 <div className="week-overview"><Badge tone="blue">{calendar?t('month'):t(parity(date,settings))}</Badge><span><CalendarDays size={15}/>{activeLessons.length} {t('totalLessons')}</span><span><FlaskConical size={15}/>{activeLessons.filter(l=>l.kind==='lab').length} {t('labsCount')}</span><span className="timezone-note"><Clock size={14}/>{settings.timezone}</span></div>
 {outside&&<Notice>{t('outOfSemester')}</Notice>}{error?<Notice error>{error}<button className="text-link" onClick={()=>setReload(v=>v+1)}>{t('retry')}</button></Notice>:loading?<Loading/>:calendar?<><div className="month-grid">{copy[lang].weekdayShort.map(d=><div key={d} className="month-weekday">{d}</div>)}{grid.map(d=>{const key=iso(d);const dayLessons=filtered.filter(l=>l.date===key);return <button key={key} className={'month-cell '+(d.getMonth()!==date.getMonth()?'other-month ':'')+(key===today?'is-today ':'')+(key===iso(date)?'selected':'')} aria-label={format(d,lang,{dateStyle:'full'})+', '+dayLessons.length+' '+t('totalLessons')} aria-pressed={key===iso(date)} onClick={()=>setDate(d)}><span className="month-date">{d.getDate()}</span><span className="month-parity">{d.getDay()===1?t(parity(d,settings)):''}</span><span className="month-events">{dayLessons.slice(0,2).map(l=><span key={l.id} className={'mini-lesson '+l.kind+(l.status==='cancelled'?' cancelled':'')}>{l.start} {title(l,lang)}</span>)}{dayLessons.length>2&&<small>+{dayLessons.length-2}</small>}</span>{dayLessons.length>0&&<span className="mobile-count">{dayLessons.length}</span>}</button>;})}</div><div className="selected-day"><div className="section-title"><h3>{format(date,lang,{weekday:'long',day:'numeric',month:'long'})}</h3><Badge>{t(parity(date,settings))}</Badge></div><div className="lesson-grid">{filtered.filter(l=>l.date===iso(date)).map(l=><LessonCard key={l.id} lesson={l} onClick={()=>setSelected(l)}/>)}</div>{!filtered.some(l=>l.date===iso(date))&&<p className="quiet-empty">{t('freeDay')}</p>}</div></>:filtered.length===0?<Empty title={t('emptyWeek')} description={t(manage?'templateHint':'emptyHint')}>{manage&&<Button onClick={()=>setAdding(true)}><Plus size={17}/>{t('addLesson')}</Button>}</Empty>:<div className="week-list">{grid.map(d=>{const key=iso(d);const items=filtered.filter(l=>l.date===key);return <section key={key} className={'day-row '+(key===today?'is-today':'')}><div className="day-label"><strong>{String(d.getDate()).padStart(2,'0')}</strong><div><span>{copy[lang].weekdays[(d.getDay()+6)%7]}</span><small>{format(d,lang,{month:'short'})}{key===today?' · '+t('today'):''}</small></div></div><div className="day-lessons">{items.length?items.map(l=><LessonCard key={l.id} lesson={l} onClick={()=>setSelected(l)}/>):<div className="free-day">{t('freeDay')}</div>}</div></section>;})}</div>}
 </section><div className="schedule-legend">{['lecture','lab','practice'].map(k=><span key={k}><span className={'legend-dot '+k}/>{t(k)}</span>)}<span>{t('updated')} · 15 {lang==='ru'?'сек.':'sec'}</span></div>
 {selected&&<LessonDetail initial={selected} revision={revision} onClose={()=>setSelected(null)}/>} {adding&&<LessonForm onClose={()=>setAdding(false)} onSave={refresh}/>}
 </>;
}
function title(l:Lesson,lang:Lang){return lang==='en'&&l.title_en?l.title_en:l.title;}
function LessonCard({lesson:l,onClick}:{lesson:Lesson;onClick:()=>void}){const {lang}=useApp();const t=useT();return <button className={'lesson-card '+l.kind+(l.status==='cancelled'?' cancelled':'')} onClick={onClick}><div className="lesson-card-top"><Badge tone={l.kind}>{t(l.kind)}</Badge><span>{l.start}–{l.end}</span></div><h3>{title(l,lang)}</h3><div className="lesson-meta"><span>{l.mode==='remote'?<Monitor size={14}/>:<MapPin size={14}/>} {l.room||t(l.mode)}</span>{l.subgroup>0&&<span><Users size={14}/> {l.subgroup}</span>}</div><div className="lesson-card-bottom">{l.status!=='confirmed'?<Badge tone={l.status==='cancelled'?'red':'amber'}>{t(l.status)}</Badge>:<span className="lesson-mode">{t(l.mode)}</span>}{l.queue_enabled&&l.status!=='cancelled'?<span className="queue-link"><ListOrdered size={15}/>{t('queue')}<ArrowRight size={14}/></span>:<ChevronRight size={15}/>}</div></button>;}

function LessonDetail({initial,revision,onClose}:{initial:Lesson;revision:number;onClose:()=>void}){const t=useT();const {lang,user,refresh}=useApp();const [lesson,setLesson]=useState(initial);const [edit,setEdit]=useState(false);const [error,setError]=useState('');useEffect(()=>{let active=true;api<Lesson>('/api/schedule/occurrences/'+initial.id).then(l=>{if(active){setLesson(l);setError('');}}).catch(e=>active&&setError(errorText(lang,e)));return()=>{active=false;};},[initial.id,revision,lang]);return <Dialog title={title(lesson,lang)} onClose={onClose} wide><div className="lesson-detail"><div className="badge-row"><Badge tone={lesson.kind}>{t(lesson.kind)}</Badge><Badge tone={lesson.status==='cancelled'?'red':lesson.status==='pending'?'amber':'green'}>{t(lesson.status)}</Badge><Badge>{t(lesson.mode)}</Badge>{lesson.demo&&<Badge tone="amber">{t('demo')}</Badge>}</div><div className="detail-facts"><span><CalendarDays size={19}/>{format(fromIso(lesson.date),lang,{weekday:'long',day:'numeric',month:'long'})}</span><span><Clock size={19}/>{lesson.start}–{lesson.end}</span><span><MapPin size={19}/>{lesson.room||'—'}</span><span><UserRound size={19}/>{lesson.teacher||'—'}</span><span><Users size={19}/>{lesson.subgroup?t('subgroup')+' '+lesson.subgroup:t('allGroups')}</span></div>{lesson.note&&<p className="lesson-note">{lesson.note}</p>}{error&&<Notice error>{error}</Notice>}<div className="button-row">{lesson.meeting_url&&lesson.status!=='cancelled'&&<a className="button secondary" href={lesson.meeting_url} target="_blank" rel="noreferrer">{t('externalMeeting')}<ExternalLink size={17}/></a>}{user.role!=='student'&&<Button variant="secondary" onClick={()=>setEdit(true)}><Settings2 size={17}/>{t('editLesson')}</Button>}</div>{lesson.queue_enabled?<QueuePanel lesson={lesson} onUpdate={refresh}/>:<p className="field-hint">{t('noQueue')}</p>}</div>{edit&&<LessonForm lesson={lesson} onClose={()=>setEdit(false)} onSave={refresh}/>}</Dialog>;}

function Queues({revision}:{revision:number}){const {lang,notify}=useApp();const t=useT();const [mine,setMine]=useState(true);const [items,setItems]=useState<{q:QueueSummary;l:Lesson}[]|null>(null);const [selected,setSelected]=useState<Lesson|null>(null);const [error,setError]=useState('');useEffect(()=>{let active=true;let busy=false;setItems(null);async function load(){if(busy)return;busy=true;try{const q=await api<QueueSummary[]>('/api/queues?mine='+mine);const rows=await Promise.all(q.map(async q=>({q,l:await api<Lesson>('/api/schedule/occurrences/'+q.occurrence_id)})));if(active){setItems(rows);setError('');}}catch(e){if(active){setError(errorText(lang,e));notify(errorText(lang,e),true);}}finally{busy=false;}}void load();const id=setInterval(()=>{if(!document.hidden)void load();},8000);return()=>{active=false;clearInterval(id);};},[mine,revision,lang,notify]);return <><div className="page-heading"><div><span className="eyebrow">CAMPUS FLOW / {t('queue')}</span><h1>{t('queues')}</h1><p>{t('myQueuesHint')}</p></div><ListOrdered className="heading-icon" size={36}/></div><div className="tabs"><button className={mine?'active':''} onClick={()=>setMine(true)}>{t('personal')}</button><button className={!mine?'active':''} onClick={()=>setMine(false)}>{t('allQueues')}</button></div>{error?<Notice error>{error}</Notice>:items===null?<Loading/>:!items.length?<Empty title={t(mine?'myQueuesEmpty':'noActiveQueues')} description={t('myQueuesHint')}><a href="#schedule" className="button primary">{t('openSchedule')}<ArrowRight size={17}/></a></Empty>:<div className="queue-cards">{items.map(({q,l})=><button key={q.id} className="queue-summary-card" onClick={()=>setSelected(l)}><div className="section-title"><Badge tone={l.kind}>{t(l.kind)}</Badge><Badge tone={l.status==='cancelled'?'red':'blue'}>{t(l.status==='cancelled'?'cancelled':Date.parse(l.ends_at)<=Date.now()?'closed':q.state)}</Badge></div><h2>{title(l,lang)}</h2><p>{format(fromIso(l.date),lang,{day:'numeric',month:'long'})} · {l.start}</p><div className="section-title"><span><Users size={17}/> {q.active_count}/{q.capacity}</span><ArrowRight size={20}/></div></button>)}</div>}{selected&&<LessonDetail initial={selected} revision={revision} onClose={()=>setSelected(null)}/>}</>;}

function Preferences({onSession}:{onSession:(s:Session)=>void}){const t=useT();const {theme,setTheme,lang,setLang,user}=useApp();const job=useJob();const [old,setOld]=useState('');const [next,setNext]=useState('');return <><div className="page-heading"><div><span className="eyebrow">CAMPUS FLOW / {t('account')}</span><h1>{t('preferences')}</h1><p>{user.name} · {roleLabel(lang,user.role)}</p></div></div><div className="preferences-grid"><section className="panel"><h2>{t('appearance')}</h2><div className="theme-choices">{([{id:'light',Icon:Sun},{id:'dark',Icon:Moon},{id:'black',Icon:Eclipse},{id:'ultra-black',Icon:Circle},{id:'system',Icon:Monitor}] as const).map(({id,Icon})=><button key={id} className={theme===id?'selected':''} aria-pressed={theme===id} onClick={()=>setTheme(id)}><span className="theme-swatch" data-preview={id} aria-hidden="true"><span/></span><span className="theme-caption"><Icon size={18}/>{t(id)}</span></button>)}</div><Field label={t('language')}><select value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="ru">Русский</option><option value="en">English</option></select></Field></section><section className="panel"><h2>{t('changePassword')}</h2><form onSubmit={e=>{e.preventDefault();void job.run(async()=>{onSession(await api<Session>('/api/auth/password','POST',{current_password:old,new_password:next}));setOld('');setNext('');},t('passwordChanged'));}}><Field label={t('currentPassword')}><input type="password" required autoComplete="current-password" value={old} onChange={e=>setOld(e.target.value)} maxLength={128}/></Field><Field label={t('newPassword')} hint={t('passwordHint')}><input type="password" required autoComplete="new-password" minLength={12} maxLength={128} value={next} onChange={e=>setNext(e.target.value)}/></Field>{job.error&&<Notice error>{job.error}</Notice>}<Button type="submit" busy={job.busy}>{t('save')}</Button></form></section></div></>;}
