export const materialCopy:Record<string,[string,string]>={
 subjectMaterials:['Материалы предмета','Subject materials'],
 materialHint:['Лекции, конспекты и учебные файлы для всей группы.','Lectures, notes and course files for your group.'],
 materialReadHint:['Можно просматривать и скачивать. Файлы добавляет руководство группы.','You can view and download files added by your group’s leadership.'],
 uploadMaterials:['Загрузить файлы','Upload files'],materialUpload:['Загрузить','Upload'],
 materialCategoryFilter:['Категория материалов','Material category'],materialCategory:['Категория','Category'],
 materialAll:['Все материалы','All materials'],materialLecture:['Лекции','Lectures'],materialNotes:['Конспекты','Notes'],materialOther:['Другое','Other'],
 materialSearch:['Найти материал','Find material'],
 materialsEmpty:['Материалов пока нет','No materials yet'],materialsEmptyHint:['Лекции и конспекты появятся здесь, когда руководство группы загрузит файлы.','Lectures and notes will appear here when your group’s leadership adds files.'],
 materialsNoResults:['Нет материалов с этими фильтрами','No materials match your filters'],
 materialTitle:['Название материала','Material title'],materialDescription:['Описание','Description'],
 materialFiles:['Файлы','Files'],materialFilesHint:['Выберите один или несколько файлов. Они загрузятся по очереди.','Select one or more files. They will upload one at a time.'],
 materialTypesHint:['Документы, растровые изображения, ZIP, аудио и видео.','Documents, raster images, ZIP archives, audio and video.'],
 materialMaxSize:['Максимум на файл','Maximum per file'],materialStorage:['Хранилище группы','Group storage'],
 materialOf:['из','of'],materialPage:['Страница','Page'],materialResults:['материалов','materials'],
 materialPreview:['Предпросмотр','Preview'],materialDownload:['Скачать','Download'],materialCancelDownload:['Отменить скачивание','Cancel download'],
 editMaterial:['Изменить материал','Edit material'],deleteMaterial:['Удалить материал','Delete material'],
 deleteMaterialHint:['Файл будет удалён для всей группы. Продолжить?','The file will be deleted for your entire group. Continue?'],
 materialSaved:['Материал сохранён','Material saved'],materialsAdded:['Файлов добавлено:','Files added:'],
 materialRemoveFile:['Убрать файл из загрузки','Remove file from upload'],materialQueued:['Ожидает загрузки','Waiting to upload'],
 materialUploading:['Загружаем','Uploading'],materialPublishing:['Сохраняем файл…','Saving file…'],materialUploaded:['Добавлен','Added'],
 materialUploadRemaining:['Загрузить оставшиеся','Upload remaining files'],materialStopUpload:['Остановить загрузку','Stop upload'],
 materialUploadStopped:['Загрузка остановлена. Уже добавленные файлы сохранены.','Upload stopped. Files already added are saved.'],
 materialUploadUncertain:['Не удалось подтвердить результат загрузки. Файл мог сохраниться.','The upload result could not be confirmed. The file may have been saved.'],
 materialCheckList:['Проверьте список материалов перед повторной загрузкой этого файла.','Check the materials list before uploading this file again.'],
 materialReload:['Обновить список материалов','Refresh materials'],
 materialUnknownAuthor:['Участник группы','Group member'],
};
export const materialErrors:Record<string,[string,string]>={
 material_too_large:['Файл превышает допустимый размер.','This file exceeds the maximum size.'],
 material_storage_full:['Хранилище группы заполнено. Удалите ненужные материалы и повторите загрузку.','Group storage is full. Remove unused materials and try again.'],
 material_type_not_allowed:['Этот тип файла не поддерживается.','This file type is not supported.'],
 material_content_mismatch:['Содержимое файла не соответствует его типу.','The file content does not match its type.'],
 material_empty:['Нельзя загрузить пустой файл.','Empty files cannot be uploaded.'],
 material_filename_invalid:['Проверьте имя файла: до 240 символов, без разделителей пути.','Check the filename: up to 240 characters, without path separators.'],
 material_unavailable:['Материал недоступен или уже удалён. Обновите список.','This material is unavailable or has been deleted. Refresh the list.'],
 storage_unavailable:['Хранилище временно недоступно. Попробуйте позже.','File storage is temporarily unavailable. Try again later.'],
 material_metadata_invalid:['Проверьте название, описание и категорию материала.','Check the material title, description and category.'],
 material_preview_failed:['Не удалось открыть изображение. Попробуйте скачать файл.','Unable to display this image. Try downloading the file.'],
 request_timeout:['Сервер не ответил вовремя. Обновите список перед повторной загрузкой.','The server did not respond in time. Refresh the list before uploading again.'],
 cancelled:['Действие отменено.','Action cancelled.'],invalid_request:['Не удалось выполнить запрос. Обновите страницу.','Unable to make this request. Reload the page.'],
};
