import type {Lang} from './types';
const ru = {
  questions:'Личные вопросы',
  notifications:'Уведомления', inboxHint:'Изменения расписания, ваша очередь и объявления группы.',
  empty:'Пока всё спокойно', emptyHint:'Новые события появятся здесь. Ничего не пропустите.',
  markAll:'Прочитать все', markRead:'Прочитано', open:'Открыть', unread:'Непрочитанные', all:'Все',
  important:'Важное объявление', understood:'Понятно', settings:'Настройки уведомлений',
  preferencesHint:'История в колокольчике сохраняется независимо от настроек push.',
  push:'Уведомления на устройстве', pushHint:'Получайте обновления, даже когда сайт закрыт.',
  enable:'Включить на этом устройстве', disable:'Отключить на этом устройстве', enabled:'Подключено',
  disabled:'Не подключено', denied:'Уведомления запрещены. Разрешите их в настройках браузера для этого сайта.',
  unsupported:'Браузер не поддерживает Web Push. История и важные объявления доступны на сайте.',
  insecure:'Откройте сайт по HTTPS, чтобы подключить уведомления.',
  ios:'На iPhone: «Поделиться» → «На экран Домой». Откройте сайт с этой иконки и включите уведомления (iOS 16.4+).',
  serverOff:'Push ещё не настроены на сервере. История уведомлений работает.',
  cancelled:'Разрешение не выдано. Уведомления можно включить позже.',
  deviceError:'Не удалось подключить устройство. Проверьте разрешение и попробуйте снова.',
  deviceLimit:'Подключено 5 устройств. Сначала удалите одно из списка.',
  accountConflict:'Подписка относится к другому аккаунту. Отключите уведомления этого сайта в браузере и подключите заново.',
  unsupportedEndpoint:'Push-сервис этого браузера пока не поддерживается. Попробуйте Chrome, Edge, Firefox или Safari.',
  test:'Отправить пробное', testSent:'Пробное уведомление добавлено. Push учитывает категории и тихие часы.',
  devices:'Ваши устройства', devicesHint:'Выйти из аккаунта — также отключить push на этом устройстве. Через 7 дней нужно войти снова.',
  noDevices:'Устройства пока не подключены.', remove:'Отключить', deviceName:'Название устройства',
  categories:'Что присылать в push', schedule:'Изменения расписания', queue:'Вызов в очереди', announcements:'Объявления',
  popups:'Показывать важные объявления поверх сайта', details:'Показывать текст на экране блокировки',
  detailsHint:'По умолчанию push не раскрывает содержание.', quiet:'Тихие часы', quietHint:'Действуют на все push, включая важные. Просроченные вызовы не отправляются позже.',
  from:'С', until:'До', timezone:'Часовой пояс', language:'Язык push', save:'Сохранить', saved:'Настройки сохранены',
  install:'Установить на телефон', installHint:'Android: меню браузера → «Установить приложение». iPhone: «Поделиться» → «На экран Домой».',
  later:'Позже', setup:'Настроить', history:'Вся история', previous:'Назад', next:'Далее', refresh:'Обновить',
  publish:'Опубликовать объявление', publishHint:'Сообщение появится у выбранных участников. Важное — также поверх сайта.',
  title:'Заголовок', body:'Текст', titleEn:'Заголовок на английском', bodyEn:'Текст на английском',
  optional:'Необязательно; без перевода показывается русский текст.', audience:'Кому', everyone:'Всей группе',
  managers:'Старостам, заместителям и админам', subgroup1:'Подгруппе 1', subgroup2:'Подгруппе 2',
  duration:'Срок показа, часов', importantToggle:'Важное: показать всплывающее объявление',
  preview:'Предпросмотр', publishConfirm:'Опубликовать для выбранных участников?', published:'Объявление опубликовано',
  withdraw:'Отозвать', withdrawn:'Отозвано', expired:'Истекло', active:'Опубликовано',
  withdrawHint:'Объявление исчезнет с сайта. Уже доставленный push нельзя забрать с устройства.',
  recent:'Опубликованные объявления', noAnnouncements:'Объявлений пока нет', retry:'Повторить',
  validation:'Проверьте поля и часы: начало и конец тихого времени должны отличаться.',
};
const en: Record<keyof typeof ru,string> = {
  questions:'Private questions',
  notifications:'Notifications', inboxHint:'Timetable changes, your queue and group announcements.',
  empty:'All quiet for now', emptyHint:'New updates will appear here. Stay in the loop.',
  markAll:'Mark all read', markRead:'Mark read', open:'Open', unread:'Unread', all:'All',
  important:'Important announcement', understood:'Got it', settings:'Notification settings',
  preferencesHint:'Your inbox stays available regardless of push settings.',
  push:'Device notifications', pushHint:'Receive updates even when the site is closed.',
  enable:'Enable on this device', disable:'Disable on this device', enabled:'Connected',
  disabled:'Not connected', denied:'Notifications are blocked. Allow them in this site’s browser settings.',
  unsupported:'This browser does not support Web Push. The inbox and important announcements still work on the site.',
  insecure:'Open this site over HTTPS to enable notifications.',
  ios:'On iPhone: Share → Add to Home Screen. Open that icon and enable notifications (iOS 16.4+).',
  serverOff:'Push is not configured on the server yet. Your inbox still works.',
  cancelled:'Permission was not granted. You can enable notifications later.',
  deviceError:'Could not connect this device. Check browser permission and try again.',
  deviceLimit:'Five devices are connected. Remove one first.',
  accountConflict:'This subscription belongs to another account. Disable this site’s notifications in the browser, then reconnect.',
  unsupportedEndpoint:'This browser’s push provider is not supported yet. Try Chrome, Edge, Firefox or Safari.',
  test:'Send a test', testSent:'Test notification queued. Push follows categories and quiet hours.',
  devices:'Your devices', devicesHint:'Signing out disables push on this device. Sign in again after 7 days.',
  noDevices:'No connected devices yet.', remove:'Disconnect', deviceName:'Device name',
  categories:'Push categories', schedule:'Timetable changes', queue:'Your turn in the queue', announcements:'Announcements',
  popups:'Show important announcements over the site', details:'Show message text on the lock screen',
  detailsHint:'Push content is private by default.', quiet:'Quiet hours', quietHint:'Applies to all push, including important updates. Expired queue calls are never sent later.',
  from:'From', until:'Until', timezone:'Time zone', language:'Push language', save:'Save', saved:'Settings saved',
  install:'Install on your phone', installHint:'Android: browser menu → Install app. iPhone: Share → Add to Home Screen.',
  later:'Later', setup:'Set up', history:'Full history', previous:'Previous', next:'Next', refresh:'Refresh',
  publish:'Publish announcement', publishHint:'Selected members receive this update. Important messages also appear over the site.',
  title:'Title', body:'Message', titleEn:'English title', bodyEn:'English message',
  optional:'Optional; the Russian text is used when no translation is provided.', audience:'Audience', everyone:'The whole group',
  managers:'Heads, deputies and admins', subgroup1:'Subgroup 1', subgroup2:'Subgroup 2',
  duration:'Display for, hours', importantToggle:'Important: show an in-app announcement',
  preview:'Preview', publishConfirm:'Publish to the selected members?', published:'Announcement published',
  withdraw:'Withdraw', withdrawn:'Withdrawn', expired:'Expired', active:'Published',
  withdrawHint:'The announcement will disappear from the site. Push already delivered cannot be recalled.',
  recent:'Published announcements', noAnnouncements:'No announcements yet', retry:'Retry',
  validation:'Check the fields and times. Quiet hours must have different start and end times.',
};
export type NKey=keyof typeof ru;
export function nt(lang:Lang,key:NKey){return (lang==='ru'?ru:en)[key];}
