import type {Lang} from './types';
const ru = {
  telegram:'Telegram', telegramHint:'Личные уведомления от бота. Работают после выхода из браузера и окончания сеанса.',
  telegramOff:'Telegram ещё не настроен на сервере. Уведомления на сайте доступны.',
  telegramConnect:'Подключить Telegram', telegramOpen:'Открыть бота и нажать «Start»',
  telegramLinkHint:'Ссылка одноразовая и действует 10 минут. Откройте её в личном чате с ботом.',
  telegramWaiting:'Ожидаем подключения в Telegram', telegramExpired:'Срок ссылки истёк. Создайте новую ссылку.',
  telegramEnabled:'Присылать в Telegram', telegramDisconnect:'Отключить Telegram',
  telegramTest:'Проверить Telegram', telegramTestSent:'Пробное отправляется сразу, включая тихие часы. Проверка доступна раз в минуту.',
  telegramUnavailable:'Telegram недоступен. Попробуйте позже.', telegramNotConnected:'Сначала подключите Telegram.',
  telegramDisabled:'Включите доставку в Telegram и сохраните настройки.',
  telegramBlocked:'Бот заблокирован. Разблокируйте его в Telegram и подключите заново.',
  telegramInactive:'Доставка остановлена: аккаунт неактивен.', telegramDelayed:'Доставка задержана. Попробуем снова автоматически.',
  telegramFailed:'Не удалось доставить сообщение. Проверьте бота и подключение.',
  telegramWebhook:'У бота настроен другой способ получения сообщений. Администратору нужно проверить подключение.',
  telegramBotChanged:'Бот изменился. Отключите прежнее подключение и создайте новое.',
  tooMany:'Слишком много попыток. Подождите минуту и попробуйте снова.',
  deviceActive:'Действует', deviceExpired:'Нужно переподключить', deviceExpiry:'До', deviceExpiryUnknown:'Срок сеанса неизвестен',
  questions:'Личные вопросы',
  notifications:'Уведомления', inboxHint:'Изменения расписания, работы, сроки сдачи и объявления группы.',
  empty:'Пока всё спокойно', emptyHint:'Новые события появятся здесь. Ничего не пропустите.',
  markAll:'Прочитать все', markRead:'Прочитано', open:'Открыть', unread:'Непрочитанные', all:'Все',
  important:'Важное объявление', understood:'Понятно', settings:'Настройки уведомлений',
  preferencesHint:'История в колокольчике сохраняется независимо от каналов доставки.',
  push:'Уведомления на устройстве', pushHint:'Получайте обновления, даже когда сайт закрыт.',
  enable:'Включить на этом устройстве', disable:'Отключить на этом устройстве', enabled:'Подключено',
  disabled:'Не подключено', denied:'Уведомления запрещены. Разрешите их в настройках браузера для этого сайта.',
  unsupported:'Браузер не поддерживает Web Push. История и важные объявления доступны на сайте.',
  insecure:'Откройте сайт по HTTPS, чтобы подключить уведомления.',
  ios:'На iPhone: «Поделиться» → «На экран Домой». Откройте сайт с этой иконки и включите уведомления (iOS 16.4+).',
  serverOff:'Push ещё не настроены на сервере. История уведомлений работает.',
  cancelled:'Разрешение не выдано. Уведомления можно включить позже.',
  deviceError:'Не удалось подключить устройство. Проверьте разрешение и попробуйте снова.',
  deviceLimit:'Подключено 5 устройств. Сначала удалите одно из списка.',
  accountConflict:'Подписка относится к другому аккаунту. Отключите уведомления этого сайта в браузере и подключите заново.',
  unsupportedEndpoint:'Push-сервис этого браузера пока не поддерживается. Попробуйте Chrome, Edge, Firefox или Safari.',
  test:'Отправить пробное', testSent:'Пробное добавлено и отправляется сразу, включая тихие часы.',
  devices:'Ваши устройства', devicesHint:'Push действует до окончания сеанса на устройстве. Войдите снова и переподключите устройство, когда срок истечёт.',
  noDevices:'Устройства пока не подключены.', remove:'Отключить', deviceName:'Название устройства',
  categories:'Что присылать', schedule:'Изменения расписания', assignments:'Работы и сроки сдачи', announcements:'Объявления',
  popups:'Показывать важные объявления поверх сайта', details:'Показывать текст на экране блокировки',
  detailsHint:'По умолчанию push и Telegram не раскрывают содержание. Текст личных вопросов никогда не отправляется.', quiet:'Тихие часы', quietHint:'Действуют на push и Telegram, включая важные сообщения. Напоминания о работах не отправляются после срока сдачи.',
  from:'С', until:'До', timezone:'Часовой пояс', language:'Язык уведомлений', save:'Сохранить', saved:'Настройки сохранены',
  install:'Установить на телефон', installHint:'Android: меню браузера → «Установить приложение». iPhone: «Поделиться» → «На экран Домой».',
  later:'Позже', setup:'Настроить', history:'Вся история', previous:'Назад', next:'Далее', refresh:'Обновить',
  publish:'Опубликовать объявление', publishHint:'Сообщение появится у выбранных участников. Важное — также поверх сайта.',
  title:'Заголовок', body:'Текст', titleEn:'Заголовок на английском', bodyEn:'Текст на английском',
  optional:'Необязательно; без перевода показывается русский текст.', audience:'Кому', everyone:'Всей группе',
  managers:'Старостам, заместителям и админам', subgroup1:'Подгруппе 1', subgroup2:'Подгруппе 2',
  duration:'Срок показа, часов', importantToggle:'Важное: показать всплывающее объявление',
  preview:'Предпросмотр', publishConfirm:'Опубликовать для выбранных участников?', published:'Объявление опубликовано',
  withdraw:'Отозвать', withdrawn:'Отозвано', expired:'Истекло', active:'Опубликовано',
  withdrawHint:'Объявление исчезнет с сайта. Уже доставленный push нельзя забрать с устройства.',
  recent:'Опубликованные объявления', noAnnouncements:'Объявлений пока нет', retry:'Повторить',
  validation:'Проверьте поля и часы: начало и конец тихого времени должны отличаться.',
};
const en: Record<keyof typeof ru,string> = {
  telegram:'Telegram', telegramHint:'Private updates from the bot. Works after browser sign-out and session expiry.',
  telegramOff:'Telegram is not configured on the server yet. Your inbox stays available.',
  telegramConnect:'Connect Telegram', telegramOpen:'Open the bot and press Start',
  telegramLinkHint:'This link works once and expires in 10 minutes. Open it in a private chat with the bot.',
  telegramWaiting:'Waiting for Telegram connection', telegramExpired:'This link expired. Create a new link.',
  telegramEnabled:'Send to Telegram', telegramDisconnect:'Disconnect Telegram',
  telegramTest:'Test Telegram', telegramTestSent:'Test sends immediately, including during quiet hours. One test per minute.',
  telegramUnavailable:'Telegram is unavailable. Try again later.', telegramNotConnected:'Connect Telegram first.',
  telegramDisabled:'Enable Telegram delivery and save your settings.',
  telegramBlocked:'The bot is blocked. Unblock it in Telegram and connect again.',
  telegramInactive:'Delivery stopped: your account is inactive.', telegramDelayed:'Delivery is delayed. We will retry automatically.',
  telegramFailed:'The message could not be delivered. Check the bot and your connection.',
  telegramWebhook:'The bot uses another update connection. Ask an administrator to check the bot setup.',
  telegramBotChanged:'The bot changed. Disconnect the old connection and create a new one.',
  tooMany:'Too many attempts. Wait a minute and try again.',
  deviceActive:'Active', deviceExpired:'Reconnect needed', deviceExpiry:'Until', deviceExpiryUnknown:'Session expiry unknown',
  questions:'Private questions',
  notifications:'Notifications', inboxHint:'Timetable changes, assignments, deadlines and group announcements.',
  empty:'All quiet for now', emptyHint:'New updates will appear here. Stay in the loop.',
  markAll:'Mark all read', markRead:'Mark read', open:'Open', unread:'Unread', all:'All',
  important:'Important announcement', understood:'Got it', settings:'Notification settings',
  preferencesHint:'Your inbox stays available regardless of delivery channels.',
  push:'Device notifications', pushHint:'Receive updates even when the site is closed.',
  enable:'Enable on this device', disable:'Disable on this device', enabled:'Connected',
  disabled:'Not connected', denied:'Notifications are blocked. Allow them in this site’s browser settings.',
  unsupported:'This browser does not support Web Push. The inbox and important announcements still work on the site.',
  insecure:'Open this site over HTTPS to enable notifications.',
  ios:'On iPhone: Share → Add to Home Screen. Open that icon and enable notifications (iOS 16.4+).',
  serverOff:'Push is not configured on the server yet. Your inbox still works.',
  cancelled:'Permission was not granted. You can enable notifications later.',
  deviceError:'Could not connect this device. Check browser permission and try again.',
  deviceLimit:'Five devices are connected. Remove one first.',
  accountConflict:'This subscription belongs to another account. Disable this site’s notifications in the browser, then reconnect.',
  unsupportedEndpoint:'This browser’s push provider is not supported yet. Try Chrome, Edge, Firefox or Safari.',
  test:'Send a test', testSent:'Test added and sends immediately, including during quiet hours.',
  devices:'Your devices', devicesHint:'Push lasts until the device session expires. Sign in and reconnect the device when its session ends.',
  noDevices:'No connected devices yet.', remove:'Disconnect', deviceName:'Device name',
  categories:'Notification categories', schedule:'Timetable changes', assignments:'Assignments and deadlines', announcements:'Announcements',
  popups:'Show important announcements over the site', details:'Show message text on the lock screen',
  detailsHint:'Push and Telegram content is private by default. Private question text is never sent.', quiet:'Quiet hours', quietHint:'Applies to push and Telegram, including important updates. Assignment reminders are never sent after their deadline.',
  from:'From', until:'Until', timezone:'Time zone', language:'Notification language', save:'Save', saved:'Settings saved',
  install:'Install on your phone', installHint:'Android: browser menu → Install app. iPhone: Share → Add to Home Screen.',
  later:'Later', setup:'Set up', history:'Full history', previous:'Previous', next:'Next', refresh:'Refresh',
  publish:'Publish announcement', publishHint:'Selected members receive this update. Important messages also appear over the site.',
  title:'Title', body:'Message', titleEn:'English title', bodyEn:'English message',
  optional:'Optional; the Russian text is used when no translation is provided.', audience:'Audience', everyone:'The whole group',
  managers:'Heads, deputies and admins', subgroup1:'Subgroup 1', subgroup2:'Subgroup 2',
  duration:'Display for, hours', importantToggle:'Important: show an in-app announcement',
  preview:'Preview', publishConfirm:'Publish to the selected members?', published:'Announcement published',
  withdraw:'Withdraw', withdrawn:'Withdrawn', expired:'Expired', active:'Published',
  withdrawHint:'The announcement will disappear from the site. Push already delivered cannot be recalled.',
  recent:'Published announcements', noAnnouncements:'No announcements yet', retry:'Retry',
  validation:'Check the fields and times. Quiet hours must have different start and end times.',
};
export type NKey=keyof typeof ru;
export function nt(lang:Lang,key:NKey){return (lang==='ru'?ru:en)[key];}
