import {useEffect,useState} from 'react';
import {Circle,Eclipse,Monitor,Moon,Sun} from 'lucide-react';
import {api} from './api';
import {memberRoles} from './i18n';
import type {Lang} from './types';
import type {Session} from './Auth';
import {Button,Field,Notice,useApp,useJob,useT} from './ui';
import Security,{OtpField} from './Security';
import CalendarTools from './CalendarTools';
import {NotificationSettings} from './Notifications';
function preference(key:string,fallback:string){try{return localStorage.getItem(key)||fallback;}catch{return fallback;}}
function savePreference(key:string,value:string){try{localStorage.setItem(key,value);}catch{}}
export default function Preferences({onSession}:{onSession:(s:Session)=>void}){const t=useT();const {theme,setTheme,lang,setLang,user}=useApp();const job=useJob();const [old,setOld]=useState('');const [next,setNext]=useState('');const [otp,setOtp]=useState('');const [reduceMotion,setReduceMotion]=useState(()=>preference('cf-reduce-motion','false')==='true');useEffect(()=>{document.documentElement.dataset.reducedMotion=String(reduceMotion);savePreference('cf-reduce-motion',String(reduceMotion));},[reduceMotion]);return <><div className="page-heading"><div><span className="eyebrow">CAMPUS FLOW / {t('account')}</span><h1>{t('preferences')}</h1><p>{user.name} · {memberRoles(lang,user)}</p></div></div><div className="preferences-grid"><section className="panel"><h2>{t('appearance')}</h2><div className="theme-choices">{([{id:'light',Icon:Sun},{id:'dark',Icon:Moon},{id:'black',Icon:Eclipse},{id:'ultra-black',Icon:Circle},{id:'system',Icon:Monitor}] as const).map(({id,Icon})=><button key={id} className={theme===id?'selected':''} aria-pressed={theme===id} onClick={()=>setTheme(id)}><span className="theme-swatch" data-preview={id} aria-hidden="true"><span/></span><span className="theme-caption"><Icon size={18}/>{t(id)}</span></button>)}</div><Field label={t('language')}><select value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="ru">Русский</option><option value="en">English</option></select></Field><label className="check-label"><input type="checkbox" checked={reduceMotion} onChange={e=>setReduceMotion(e.target.checked)}/>{t('reduceMotion')}</label><p className="field-hint">{t('motionHint')}</p></section><section className="panel"><h2>{t('changePassword')}</h2><form onSubmit={e=>{e.preventDefault();void job.run(async()=>{onSession(await api<Session>('/api/auth/password','POST',{current_password:old,new_password:next,code:otp}));setOld('');setNext('');setOtp('');},t('passwordChanged'));}}><Field label={t('currentPassword')}><input type="password" required autoComplete="current-password" value={old} onChange={e=>setOld(e.target.value)} maxLength={128}/></Field><Field label={t('newPassword')} hint={t('passwordHint')}><input type="password" required autoComplete="new-password" minLength={12} maxLength={128} value={next} onChange={e=>setNext(e.target.value)}/></Field><OtpField value={otp} onChange={setOtp} required={false}/>{job.error&&<Notice error>{job.error}</Notice>}<Button type="submit" busy={job.busy}>{t('save')}</Button></form></section><Security/><CalendarTools/><NotificationSettings/></div></>;}
