import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Check,Clock,Hash,ListOrdered,Pause,Play,Settings2,UserRound,Users,X,History} from 'lucide-react';
import {api,actionKey} from './api';
import type {Lesson,QueueDetail,QueueSummary} from './types';
import {errorText} from './i18n';
import {locale} from './date';
import {Badge,Button,Confirm,Dialog,Empty,Field,Loading,Notice,useApp,useJob,useT} from './ui';

type PendingConfirm={action:string;entry_id?:string};
export default function QueuePanel({lesson,onUpdate}:{lesson:Lesson;onUpdate:()=>void}){
 const t=useT();const {user,lang,settings}=useApp();const manage=user.role!=='student';const [q,setQ]=useState<QueueDetail|null>(null);const [loading,setLoading]=useState(true);const [offline,setOffline]=useState(false);const [task,setTask]=useState('');const [confirm,setConfirm]=useState<PendingConfirm|null>(null);const [config,setConfig]=useState(false);const [history,setHistory]=useState(false);const job=useJob();const requestRef=useRef<{body:string;key:string}|null>(null);const qRef=useRef<QueueDetail|null>(null);qRef.current=q;
 useEffect(()=>{let mounted=true;let inFlight=false;async function load(){if(inFlight||document.hidden)return;inFlight=true;try{const list=await api<QueueSummary[]>(`/api/queues?occurrence_id=${lesson.id}`);const data=list[0]?await api<QueueDetail>(`/api/queues/${list[0].id}`):null;if(mounted){setQ(data);setOffline(false);}}catch{if(mounted)setOffline(true);}finally{inFlight=false;if(mounted)setLoading(false);}}void load();const interval=setInterval(load,4000);document.addEventListener('visibilitychange',load);return()=>{mounted=false;clearInterval(interval);document.removeEventListener('visibilitychange',load);};},[lesson.id]);
 async function command(action:string,extra:Record<string,unknown>={}){
  const current=qRef.current;if(!current)return;
  const body={action,...extra,...(action!=='join'&&action!=='leave'?{revision:current.revision}:{})};const serialized=JSON.stringify(body);
  if(requestRef.current?.body!==serialized)requestRef.current={body:serialized,key:actionKey()};
  const result=await api<QueueDetail>(`/api/queues/${current.id}/actions`,'POST',body,{'Idempotency-Key':requestRef.current!.key});requestRef.current=null;setQ(result);onUpdate();return result;
 }
 if(loading)return <Loading/>;
 if(!q)return <section className="queue-section"><Empty title={t('noQueue')} description={manage?t('queueConfigHint'):t('noNames')}>{manage&&lesson.queue_enabled&&lesson.status!=='cancelled'&&<Button busy={job.busy} onClick={()=>void job.run(async()=>{const created=await api<QueueDetail>('/api/queues','POST',{occurrence_id:lesson.id});setQ(created);onUpdate();})}><ListOrdered size={17}/>{t('createQueue')}</Button>}</Empty>{(offline||job.error)&&<Notice error>{job.error||t('offline')}</Notice>}</section>;
 const called=q.entries.find(e=>e.status==='called');const canJoin=!q.blocked_reason&&q.entries.length<q.capacity&&(q.lesson.subgroup===0||q.lesson.subgroup===user.subgroup)&&!q.history.some(e=>e.user_id===user.id&&e.status==='done');
 const started=Date.parse(q.server_time)>=Date.parse(q.lesson.starts_at);
 const ahead=q.my_position?Math.max(0,q.my_position-1):0;
 return <section className="queue-section">
  <div className="section-title"><h3><ListOrdered size={20}/>{t('queue')}</h3><Badge tone={q.state==='open'&&!q.blocked_reason?'green':'neutral'}>{t(q.blocked_reason==='lesson_cancelled'?'cancelled':q.state)}</Badge></div>
  {offline&&<Notice error>{t('offline')}</Notice>}{job.error&&<Notice error>{job.error}</Notice>}
  {q.my_entry&&<div className={`my-position ${q.my_entry.status==='called'?'called':''}`} aria-live="polite"><div className="position-number">{q.my_entry.status==='called'?<Check size={36}/>:String(q.my_position).padStart(2,'0')}</div><div><strong>{q.my_entry.status==='called'?t('calledYou'):t('myPlace')}</strong><p>{q.my_entry.status==='called'?t('calledHint'):`${t('beforeYou')}: ${ahead} · ${t('approx')}: ~${ahead*q.minutes_per_student} ${t('minutes')}`}</p></div></div>}
  {q.blocked_reason&&<Notice>{errorText(lang,{code:q.blocked_reason})}{q.blocked_reason==='queue_too_early'&&<> {t('waitOpen')}: {new Intl.DateTimeFormat(locale(lang),{dateStyle:'short',timeStyle:'short',timeZone:settings.timezone}).format(new Date(q.opens_at))}.</>}</Notice>}
  <div className="queue-meta"><span><Users size={15}/>{q.entries.length} / {q.capacity}</span><span><Clock size={15}/>~{q.minutes_per_student} {t('minutes')}</span><span className="live-label">{t('queueUpdated')}</span></div>
  <div className="queue-list">{q.entries.length===0?<p className="quiet-empty">{t('emptyQueue')}</p>:q.entries.map((e,i)=><div key={e.id} className={`queue-row ${e.user_id===user.id?'self':''} ${e.status==='called'?'is-called':''}`}><span className="queue-rank">{e.status==='called'?<ArrowRight size={17}/>:String(i+1).padStart(2,'0')}</span><div className="avatar small">{e.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div><div className="queue-person"><strong>{e.name}</strong><span>{e.task}</span></div><Badge tone={e.status==='called'?'blue':'neutral'}>{t(e.status)}</Badge>{manage&&<button className="icon-button small" aria-label={`${t('remove')} ${e.name}`} onClick={()=>setConfirm({action:'remove',entry_id:e.id})}><X size={16}/></button>}</div>)}</div>
  {q.my_entry&&q.my_entry.status==='waiting'?<Button variant="secondary" busy={job.busy} onClick={()=>void job.run(()=>command('leave'))}>{t('leave')}</Button>:!q.my_entry&&<form className="join-form" onSubmit={e=>{e.preventDefault();void job.run(()=>command('join',{task}));}}><Field label={t('task')}><input required maxLength={120} placeholder={t('taskPlaceholder')} value={task} onChange={e=>setTask(e.target.value)} disabled={!canJoin||offline}/></Field><Button type="submit" busy={job.busy} disabled={!canJoin||offline}><ListOrdered size={18}/>{t('join')}<ArrowRight size={17}/></Button></form>}
  <p className="field-hint">{t('queueHint')}</p>
  {manage&&<div className="queue-controls"><div className="section-title"><h4>{t('queueAdmin')}</h4><button className="icon-button" onClick={()=>setConfig(true)} aria-label={t('configureQueue')}><Settings2 size={18}/></button></div><div className="button-row">{q.state!=='open'||q.blocked_reason==='lesson_changed'?<Button busy={job.busy} disabled={offline} onClick={()=>void job.run(()=>command('open'))}><Play size={16}/>{t('openQueue')}</Button>:<Button variant="secondary" busy={job.busy} disabled={offline} onClick={()=>void job.run(()=>command('pause'))}><Pause size={16}/>{t('pauseQueue')}</Button>}<Button variant="secondary" busy={job.busy} disabled={offline||!!called||!!q.blocked_reason||!q.entries.length||!started} onClick={()=>void job.run(()=>command('next'))}><ArrowRight size={16}/>{t('callNext')}</Button>{q.state!=='closed'&&<Button variant="ghost" onClick={()=>setConfirm({action:'close'})}>{t('closeQueue')}</Button>}</div>{!started&&<p className="field-hint">{t('waitingStart')}</p>}{called&&<div className="current-student"><strong><UserRound size={18}/>{called.name}</strong><div className="button-row"><Button busy={job.busy} disabled={offline} onClick={()=>void job.run(()=>command('done',{entry_id:called.id}))}><Check size={16}/>{t('markDone')}</Button><Button variant="secondary" busy={job.busy} disabled={offline} onClick={()=>void job.run(()=>command('skip',{entry_id:called.id}))}>{t('skip')}</Button></div></div>}</div>}
  <details className="rules-details"><summary>{t('queueRules')}</summary><p>{t('queueRulesText')}</p><p>{t('queuePrivacy')}</p></details>
  <button className="text-link" onClick={()=>setHistory(!history)}><History size={16}/>{t('history')} ({q.history.length})</button>{history&&<div className="queue-history">{q.history.length?q.history.slice().reverse().map(e=><div key={e.id}><span><Hash size={13}/>{e.ticket} · {e.name}<small>{e.task}</small></span><Badge>{t(e.status)}</Badge></div>):<p className="muted">{t('noHistory')}</p>}</div>}
  {confirm&&<Confirm title={t(confirm.action==='close'?'closeQueue':'remove')} description={confirm.action==='close'?t('closeConfirm'):t('reason')} reason onClose={()=>setConfirm(null)} onConfirm={reason=>command(confirm.action,{entry_id:confirm.entry_id||'',reason})}/>}
  {config&&<QueueConfig q={q} onClose={()=>setConfig(false)} onSave={values=>command('configure',values)}/>}
 </section>;
}
function QueueConfig({q,onClose,onSave}:{q:QueueDetail;onClose:()=>void;onSave:(v:Record<string,number>)=>Promise<unknown>}){const t=useT();const job=useJob();const [capacity,setCapacity]=useState(q.capacity);const [minutes,setMinutes]=useState(q.minutes_per_student);const [hours,setHours]=useState(q.opens_before_hours);return <Dialog title={t('configureQueue')} onClose={onClose}><form onSubmit={e=>{e.preventDefault();void job.run(async()=>{await onSave({capacity,minutes_per_student:minutes,opens_before_hours:hours});onClose();});}}><Field label={t('capacity')}><input type="number" min={Math.max(1,q.entries.length)} max={100} value={capacity} onChange={e=>setCapacity(+e.target.value)}/></Field><Field label={t('perStudent')}><input type="number" min={1} max={60} value={minutes} onChange={e=>setMinutes(+e.target.value)}/></Field><Field label={t('opensHours')}><input type="number" min={0} max={168} value={hours} onChange={e=>setHours(+e.target.value)}/></Field>{job.error&&<Notice error>{job.error}</Notice>}<div className="form-actions"><Button variant="secondary" onClick={onClose}>{t('cancel')}</Button><Button type="submit" busy={job.busy}>{t('save')}</Button></div></form></Dialog>;}
