import {useEffect,useState} from 'react';
import {KeyRound,ShieldCheck} from 'lucide-react';
import {api} from './api';
import {errorText} from './i18n';
import {Button,Confirm,Dialog,Field,Loading,Notice,useApp,useJob,useT} from './ui';
import type {Session} from './Auth';
type SecurityStatus={enabled:boolean;recovery_remaining:number};
type Device={id:string;current:boolean;device:string;created_at:string;expires:string};
type Setup={secret:string;uri:string};
export function OtpField({value,onChange,required=true}:{value:string;onChange:(v:string)=>void;required?:boolean}){const t=useT();return <Field label={t('otpCode')} hint={t(required?'otpHint':'otpOptional')}><input aria-label={t('otpCode')} autoComplete="one-time-code" autoCapitalize="characters" spellCheck={false} required={required} minLength={required?6:undefined} maxLength={40} value={value} onChange={e=>onChange(e.target.value)}/></Field>;}
export function MfaSignIn({challenge,onSession,onBack}:{challenge:string;onSession:(s:Session)=>void;onBack:()=>void}){const t=useT();const job=useJob();const [code,setCode]=useState('');return <form onSubmit={e=>{e.preventDefault();void job.run(async()=>onSession(await api<Session>('/api/auth/login/verify','POST',{challenge,code})));}}><h3>{t('mfaLogin')}</h3><OtpField value={code} onChange={setCode}/>{job.error&&<Notice error>{job.error}</Notice>}<div className="button-row"><Button type="submit" busy={job.busy}>{t('login')}</Button><Button variant="secondary" disabled={job.busy} onClick={onBack}>{t('backLogin')}</Button></div></form>;}
export default function Security(){
 const t=useT();const {lang,refresh}=useApp();const [status,setStatus]=useState<SecurityStatus|null>(null);const [devices,setDevices]=useState<Device[]>([]);const [error,setError]=useState('');const [reload,setReload]=useState(0);const [action,setAction]=useState<'setup'|'disable'|'recovery'|null>(null);const [revoke,setRevoke]=useState<Device|'others'|null>(null);
 useEffect(()=>{let active=true;void Promise.all([api<SecurityStatus>('/api/auth/security'),api<Device[]>('/api/auth/sessions')]).then(([s,d])=>{if(active){setStatus(s);setDevices(d);setError('');}}).catch(e=>active&&setError(errorText(lang,e)));return()=>{active=false;};},[lang,reload]);
 return <><section className="panel"><div className="section-title"><h2>{t('mfaTitle')}</h2><ShieldCheck size={23}/></div><p className="muted">{t('mfaHint')}</p>{error?<Notice error>{error}<Button variant="ghost" onClick={()=>setReload(v=>v+1)}>{t('retry')}</Button></Notice>:!status?<Loading/>:<><p><strong>{t(status.enabled?'enabled':'disabled')}</strong>{status.enabled&&<> · {t('remainingCodes')}: {status.recovery_remaining}</>}</p><div className="button-row">{status.enabled?<><Button variant="secondary" onClick={()=>setAction('recovery')}>{t('regenerateCodes')}</Button><Button variant="ghost" onClick={()=>setAction('disable')}>{t('mfaDisable')}</Button></>:<Button onClick={()=>setAction('setup')}><KeyRound size={17}/>{t('mfaSetup')}</Button>}</div></>}</section><section className="panel"><h2>{t('sessions')}</h2><div className="session-list">{devices.map(d=><article key={d.id}><div><strong>{d.current?t('currentSession'):deviceName(d.device,t('unknownDevice'))}</strong><small>{t('sessionCreated')}: {new Date(d.created_at).toLocaleString(lang==='ru'?'ru-RU':'en-GB')}</small><details><summary>{t('detailsHistory')}</summary><p>{d.device||t('unknownDevice')}</p></details></div>{!d.current&&<Button variant="ghost" onClick={()=>setRevoke(d)}>{t('endSession')}</Button>}</article>)}</div><Button variant="secondary" disabled={!devices.some(d=>!d.current)} onClick={()=>setRevoke('others')}>{t('endOtherSessions')}</Button></section>{action&&<FactorDialog action={action} onClose={()=>{setAction(null);setReload(v=>v+1);}}/>}{revoke&&<Confirm title={t(revoke==='others'?'endOtherSessions':'endSession')} description={revoke==='others'?t('mfaRevokeHint'):deviceName(revoke.device,t('unknownDevice'))} onClose={()=>setRevoke(null)} onConfirm={async()=>{await api('/api/auth/sessions/'+(revoke==='others'?'others':revoke.id),'DELETE');setReload(v=>v+1);refresh();}}/>}</>;
}
function deviceName(agent:string,fallback:string){const browser=/Edg\//.test(agent)?'Edge':/Firefox\//.test(agent)?'Firefox':/Chrome\//.test(agent)?'Chrome':/Safari\//.test(agent)?'Safari':fallback;const system=/Android/.test(agent)?'Android':/iPhone|iPad/.test(agent)?'iOS':/Windows/.test(agent)?'Windows':/Macintosh/.test(agent)?'macOS':/Linux/.test(agent)?'Linux':'';return browser+(system?' · '+system:'');}
function FactorDialog({action,onClose}:{action:'setup'|'disable'|'recovery';onClose:()=>void}){
 const t=useT();const job=useJob();const {notify}=useApp();const [password,setPassword]=useState('');const [code,setCode]=useState('');const [setup,setSetup]=useState<Setup|null>(null);const [codes,setCodes]=useState<string[]|null>(null);
 async function submit(){if(action==='setup'&&!setup){setSetup(await api<Setup>('/api/auth/security/setup','POST',{password}));setPassword('');return;}if(action==='setup'){const result=await api<{recovery_codes:string[]}>('/api/auth/security/enable','POST',{code});setCodes(result.recovery_codes);setSetup(null);setCode('');return;}const result=await api<{recovery_codes?:string[]}>('/api/auth/security/'+action,'POST',{password,code});setPassword('');setCode('');if(result.recovery_codes)setCodes(result.recovery_codes);else onClose();}
 return <Dialog title={t(codes?'recoveryCodes':action==='setup'?'mfaSetup':action==='disable'?'mfaDisable':'regenerateCodes')} onClose={()=>!job.busy&&!codes&&onClose()}>{codes?<><Notice>{t('recoveryHint')}</Notice><textarea className="recovery-codes" aria-label={t('recoveryCodes')} readOnly rows={10} value={codes.join('\n')} onFocus={e=>e.target.select()}/><div className="button-row"><Button variant="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(codes.join('\n'));notify(t('copied'));}catch{document.querySelector<HTMLTextAreaElement>('.recovery-codes')?.select();}}}>{t('copy')}</Button><Button onClick={onClose}>{t('codesSaved')}</Button></div></>:<form onSubmit={e=>{e.preventDefault();void job.run(submit);}}>{setup?<><p>{t('mfaEnrollHint')}</p><Field label={t('mfaKey')}><input readOnly className="secret-key" value={setup.secret} onFocus={e=>e.target.select()}/></Field><a className="text-link" href={setup.uri}>{t('openAuthenticator')}</a><OtpField value={code} onChange={setCode}/></>:<><p className="muted">{t(action==='recovery'?'regenerateHint':'mfaRevokeHint')}</p><Field label={t('currentPassword')}><input type="password" required autoComplete="current-password" maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/></Field>{action!=='setup'&&<OtpField value={code} onChange={setCode}/>}</>}{job.error&&<Notice error>{job.error}</Notice>}<div className="form-actions"><Button variant="secondary" disabled={job.busy} onClick={onClose}>{t('cancel')}</Button><Button type="submit" busy={job.busy} variant={action==='disable'?'danger':'primary'}>{t(setup?'mfaEnable':action==='setup'?'mfaSetup':action==='disable'?'mfaDisable':'regenerateCodes')}</Button></div></form>}</Dialog>;
}
