import {useState} from 'react';
import {ArrowLeft,ArrowRight,BookOpen,CalendarDays,CheckCircle2,ExternalLink,Link,Plus,RefreshCw,Search,Settings2,Trash2,UserRound} from 'lucide-react';
import {api} from './api';
import {addDays,dateInZone,format,fromIso,iso} from './date';
import {assignmentSubgroup} from './study';
import type {Assignment,Lesson,Subject,SubjectLink} from './types';
import {Badge,Button,Confirm,Dialog,Empty,Field,IconButton,Loading,Notice,useApp,useJob,useT} from './ui';
import {LessonCard,LessonDetail,lessonTitle} from './Lessons';
import AssignmentCard from './AssignmentCard';
import {AssignmentForm} from './Assignments';
import {SubgroupFilter,useResource,useStudyFilters} from './useStudy';
import SubjectMaterials from './Materials';

export default function Subjects({revision,subjectKey}:{revision:number;subjectKey?:string}){
 return subjectKey?<SubjectPage key={subjectKey} revision={revision} subjectKey={subjectKey}/>:<SubjectList revision={revision}/>;
}

function SubjectList({revision}:{revision:number}){
 const {lang,settings}=useApp();const t=useT();const subjects=useResource<Subject[]>('/api/schedule/subjects',revision);const [search,setSearch]=useState('');
 const shown=(subjects.data||[]).filter(s=>(s.title+' '+s.title_en+' '+s.title_en_auto+' '+s.teacher).toLocaleLowerCase().includes(search.toLocaleLowerCase())).sort((a,b)=>lessonTitle(a,lang).localeCompare(lessonTitle(b,lang),lang));
 return <><div className="page-heading"><div><span className="eyebrow">{settings.group} / CAMPUS FLOW</span><h1>{t('subjects')}</h1><p>{t('subjectHint')}</p></div><BookOpen className="heading-icon" size={30}/></div><div className="academic-toolbar"><div className="search-control"><Search size={17}/><input type="search" aria-label={t('subjectSearch')} placeholder={t('subjectSearch')} value={search} onChange={e=>setSearch(e.target.value)}/></div><span className="muted subject-count">{shown.length} / {subjects.data?.length||0}</span><IconButton label={t('refresh')} onClick={subjects.reload}><RefreshCw size={18}/></IconButton></div>{subjects.error&&<Notice error>{subjects.error}<button onClick={subjects.reload}>{t('retry')}</button></Notice>}{subjects.loading?<Loading/>:!shown.length?<Empty title={t('noSubjects')} description={t('noSubjectsHint')}>{search&&<Button variant="secondary" onClick={()=>setSearch('')}>{t('resetFilters')}</Button>}</Empty>:<div className="subject-grid">{shown.map((subject,index)=><a key={subject.key} href={'#subject/'+encodeURIComponent(subject.key)} className="subject-card"><div className="subject-card-top"><span className={'subject-symbol subject-color-'+index%3}><BookOpen size={22}/></span><ArrowRight size={19}/></div><h2>{lessonTitle(subject,lang)}</h2><p className="subject-teacher"><UserRound size={15}/>{subject.teacher||t('subjectUnassignedTeacher')}</p>{subject.requirements&&<p className="subject-requirements-preview">{subject.requirements}</p>}<div className="subject-card-foot"><span><Link size={14}/>{subject.links.length}</span><span>{t('openSubject')}<ArrowRight size={14}/></span></div></a>)}</div>}</>;
}

function SubjectPage({revision,subjectKey}:{revision:number;subjectKey:string}){
 const t=useT();const {user,settings,lang}=useApp();const manage=user.role!=='student';const {filters,update}=useStudyFilters();const today=iso(dateInZone(settings.timezone));const end=iso(addDays(fromIso(today),27));
 const subject=useResource<Subject>(`/api/schedule/subjects/${encodeURIComponent(subjectKey)}`,revision);
 const lessons=useResource<Lesson[]>(`/api/schedule/occurrences?start=${today}&end=${end}&subgroup=${filters.subgroup}`,revision,15000);
 const assignments=useResource<Assignment[]>(`/api/schedule/assignments?subject_key=${encodeURIComponent(subjectKey)}&subgroup=${assignmentSubgroup(filters.subgroup,user)}`,revision,60000);
 const [editing,setEditing]=useState(false);const [selected,setSelected]=useState<Lesson|null>(null);const [form,setForm]=useState<Assignment|null|false>(false);const [archive,setArchive]=useState<Assignment|null>(null);const [showDone,setShowDone]=useState(false);
 const info=subject.data;const classes=(lessons.data||[]).filter(l=>l.subject_key===subjectKey||(!l.subject_key&&l.title===info?.title)).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start));const dates=[...new Set(classes.map(l=>l.date))];
 const work=(assignments.data||[]).filter(a=>showDone||a.progress.status!=='done').sort((a,b)=>(a.due_at||'9999').localeCompare(b.due_at||'9999'));
 const replace=(assignment:Assignment)=>assignments.setData(previous=>previous?.map(a=>a.id===assignment.id?assignment:a)||null);
 const reload=()=>{subject.reload();lessons.reload();assignments.reload();};
 if(subject.loading)return <Loading/>;
 if(!info)return <><a className="text-link breadcrumb" href="#subjects"><ArrowLeft size={16}/>{t('subjects')}</a>{subject.error&&<Notice error>{subject.error}</Notice>}<Empty title={t('subjectMissing')} description={t('subjectUnavailableHint')}><Button onClick={reload}>{t('retry')}</Button><a className="button secondary" href="#subjects">{t('openSubjects')}</a></Empty></>;
 return <>
  <a className="text-link breadcrumb" href="#subjects"><ArrowLeft size={16}/>{t('subjects')}</a>
  <div className="page-heading"><div><span className="eyebrow">{settings.group} / {t('subjects')}</span><h1>{lessonTitle(info,lang)}</h1><p className="subject-teacher"><UserRound size={16}/>{info.teacher||classes.find(lesson=>lesson.teacher)?.teacher||t('subjectUnassignedTeacher')}</p></div><div className="heading-actions">{manage&&<Button variant="secondary" onClick={()=>setEditing(true)}><Settings2 size={17}/>{t('editSubject')}</Button>}<IconButton label={t('refresh')} onClick={reload}><RefreshCw size={18}/></IconButton></div></div>
  {subject.error&&<Notice error>{subject.error}</Notice>}
  <div className="subject-info-grid"><section className="panel subject-requirements"><h2><CheckCircle2 size={20}/>{t('requirements')}</h2><p className={info.requirements?'pre-wrap':'muted'}>{info.requirements||t('noRequirements')}</p></section><section className="panel subject-resources"><h2><Link size={20}/>{t('subjectLinks')}</h2>{info.links.length?<div className="subject-resource-list">{info.links.filter(link=>link.url.startsWith('https://')).map((link,i)=><a key={i} href={link.url} target="_blank" rel="noreferrer"><span>{link.label||link.url}</span><ExternalLink size={16}/></a>)}</div>:<p className="muted">{t('noSubjectLinks')}</p>}</section></div>
  <SubjectMaterials subjectKey={subjectKey} revision={revision}/>
  <div className="subject-study-grid"><section className="subject-work"><div className="section-title"><h2>{t('assignments')}<Badge>{assignments.data?.length||0}</Badge></h2>{manage&&<Button onClick={()=>setForm(null)}><Plus size={17}/>{t('addAssignment')}</Button>}</div><p className="personal-status-note">{t('personalStatuses')}</p><label className="check-label completed-toggle"><input type="checkbox" checked={showDone} onChange={e=>setShowDone(e.target.checked)}/>{t('showCompleted')}</label>{assignments.error&&<Notice error>{assignments.error}<button onClick={assignments.reload}>{t('retry')}</button></Notice>}{assignments.loading?<Loading/>:!work.length?<Empty title={t(assignments.data?.length?'allCaughtUp':'noAssignments')} description={t('noAssignmentsHint')}/>:<div className="subject-assignment-list">{work.map(a=><AssignmentCard key={a.id} assignment={a} subject={info} onUpdate={replace} onReload={assignments.reload} onEdit={manage?()=>setForm(a):undefined} onArchive={manage?()=>setArchive(a):undefined}/>)}</div>}</section>
   <section className="subject-classes"><div className="section-title"><h2><CalendarDays size={20}/>{t('subjectLessons')}</h2></div><p className="field-hint">{t('subjectLessonRange')}</p><SubgroupFilter value={filters.subgroup} onChange={subgroup=>update({subgroup})}/>{lessons.error&&<Notice error>{lessons.error}<button onClick={lessons.reload}>{t('retry')}</button></Notice>}{lessons.loading?<Loading/>:!classes.length?<p className="quiet-empty">{t('noSubjectLessons')}</p>:dates.map(date=><div className="subject-class-day" key={date}><h3>{format(fromIso(date),lang,{weekday:'short',day:'numeric',month:'short'})}</h3><div>{classes.filter(l=>l.date===date).map(l=><LessonCard key={l.id} lesson={l} compact onClick={()=>setSelected(l)}/>)}</div></div>)}</section></div>
  {editing&&<SubjectForm subject={info} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);subject.reload();}} onReload={()=>{setEditing(false);subject.reload();}}/>}
  {form!==false&&<AssignmentForm subjects={[info]} initial={form||undefined} subjectKey={info.key} onClose={()=>setForm(false)} onSaved={()=>{setForm(false);assignments.reload();}} onReload={()=>{setForm(false);assignments.reload();}}/>}
  {archive&&<Confirm title={t('archiveAssignment')} description={t('archiveAssignmentHint')} onClose={()=>setArchive(null)} onConfirm={async()=>{await api(`/api/schedule/assignments/${archive.id}?revision=${archive.revision}`,'DELETE');assignments.reload();}}/>}
  {selected&&<LessonDetail initial={selected} revision={revision} onClose={()=>setSelected(null)}/>}
 </>;
}

function SubjectForm({subject,onClose,onSaved,onReload}:{subject:Subject;onClose:()=>void;onSaved:()=>void;onReload:()=>void}){
 const t=useT();const {notify}=useApp();const job=useJob();const [teacher,setTeacher]=useState(subject.teacher);const [requirements,setRequirements]=useState(subject.requirements);const [links,setLinks]=useState<SubjectLink[]>(subject.links.map(link=>({...link})));
 const editLink=(index:number,key:keyof SubjectLink,value:string)=>setLinks(items=>items.map((link,i)=>index===i?{...link,[key]:value}:link));
 return <Dialog title={t('editSubject')} onClose={()=>!job.busy&&onClose()} wide><form onSubmit={e=>{e.preventDefault();void job.run(async()=>{await api(`/api/schedule/subjects/${encodeURIComponent(subject.key)}`,'PATCH',{revision:subject.revision,teacher:teacher.trim(),requirements:requirements.trim(),links:links.map(link=>({label:link.label.trim(),url:link.url.trim()}))});notify(t('subjectSaved'));onSaved();});}}><fieldset className="form-fieldset" disabled={job.busy}><Field label={t('teacher')}><input maxLength={100} autoFocus value={teacher} onChange={e=>setTeacher(e.target.value)}/></Field><Field label={t('requirements')}><textarea rows={6} maxLength={10000} value={requirements} onChange={e=>setRequirements(e.target.value)}/></Field><h3 className="subject-form-links-title">{t('subjectLinks')}</h3>{links.map((link,i)=><div className="subject-link-form" key={i}><Field label={t('linkLabel')}><input required maxLength={120} value={link.label} onChange={e=>editLink(i,'label',e.target.value)}/></Field><Field label={t('linkUrl')}><input required type="url" pattern="https://.*" maxLength={500} value={link.url} onChange={e=>editLink(i,'url',e.target.value)} placeholder="https://"/></Field><IconButton label={t('delete')+' · '+(link.label||i+1)} onClick={()=>setLinks(items=>items.filter((_,index)=>index!==i))}><Trash2 size={17}/></IconButton></div>)}<Button variant="secondary" disabled={links.length>=20} onClick={()=>setLinks(items=>[...items,{label:'',url:''}])}><Plus size={17}/>{t('addLink')}</Button></fieldset>{job.error&&<Notice error>{job.error}<button type="button" onClick={onReload}>{t('refreshConflict')}</button></Notice>}<div className="form-actions"><Button variant="secondary" onClick={onClose} disabled={job.busy}>{t('cancel')}</Button><Button type="submit" busy={job.busy}>{t('save')}</Button></div></form></Dialog>;
}
