import {createContext,useContext,useEffect,useId,useRef,useState,type ReactNode} from 'react';
import {AlertCircle,CheckCircle2,LoaderCircle,X,ArrowRight,Inbox} from 'lucide-react';
import type {Lang,Theme,User,Settings} from './types';
import {errorText,tx} from './i18n';
export type Context={lang:Lang;setLang:(l:Lang)=>void;theme:Theme;setTheme:(t:Theme)=>void;user:User;settings:Settings;refresh:()=>void;notify:(message:string,error?:boolean)=>void;};
export const AppContext=createContext<Context>(null!);
export function useApp(){return useContext(AppContext);}
export function useT(){const {lang}=useApp();return (key:string)=>tx(lang,key);}
export function IconButton({label,children,...props}:{label:string;children:ReactNode}&React.ButtonHTMLAttributes<HTMLButtonElement>){return <button type="button" className="icon-button" aria-label={label} title={label} {...props}>{children}</button>;}
export function Button({children,variant='primary',busy=false,...props}:{children:ReactNode;variant?:'primary'|'secondary'|'danger'|'ghost';busy?:boolean}&React.ButtonHTMLAttributes<HTMLButtonElement>){return <button type="button" {...props} disabled={props.disabled||busy} className={`button ${variant} ${props.className||''}`}>{busy?<LoaderCircle size={17} className="spin"/>:null}{children}</button>;}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>;}
export function Empty({title,description,children}:{title:string;description?:string;children?:ReactNode}){return <div className="empty"><div className="empty-icon"><Inbox size={28}/></div><h3>{title}</h3>{description&&<p>{description}</p>}{children}</div>;}
export function Notice({children,error=false}:{children:ReactNode;error?:boolean}){return <div className={`notice ${error?'error':''}`} role={error?'alert':'status'}><AlertCircle size={18}/><span>{children}</span></div>;}
export function Loading(){const t=useT();return <div className="loading" role="status"><LoaderCircle className="spin" size={22}/>{t('loading')}</div>;}
export function Dialog({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){const ref=useRef<HTMLDialogElement>(null);const id=useId();const t=useT();useEffect(()=>{const el=ref.current!;el.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;el.close();};},[]);return <dialog ref={ref} className={`dialog ${wide?'wide':''}`} aria-labelledby={id} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)onClose();}}}><div className="dialog-head"><h2 id={id}>{title}</h2><IconButton label={t('close')} onClick={onClose}><X size={21}/></IconButton></div><div className="dialog-body">{children}</div></dialog>;}
export function Confirm({title,description,onClose,onConfirm,reason=false}:{title:string;description:string;onClose:()=>void;onConfirm:(reason:string)=>Promise<unknown>;reason?:boolean}){const t=useT();const {lang}=useApp();const [value,setValue]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');return <Dialog title={title} onClose={()=>!busy&&onClose()}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await onConfirm(value);onClose();}catch(err){setError(errorText(lang,err));}finally{setBusy(false);}}}><p className="muted">{description}</p>{reason&&<Field label={t('reason')}><textarea required maxLength={250} autoFocus value={value} onChange={e=>setValue(e.target.value)} placeholder={t('reasonPlaceholder')}/></Field>}{error&&<Notice error>{error}</Notice>}<div className="form-actions"><Button variant="secondary" onClick={onClose} disabled={busy}>{t('cancel')}</Button><Button type="submit" variant="danger" busy={busy}>{t('confirm')}</Button></div></form></Dialog>;}
export function useJob(){const {lang,notify}=useApp();const [busy,setBusy]=useState(false);const [error,setError]=useState('');return {busy,error,run:async<T,>(fn:()=>Promise<T>,success?:string):Promise<T|undefined>=>{setBusy(true);setError('');try{const value=await fn();if(success)notify(success);return value;}catch(e){setError(errorText(lang,e));return undefined;}finally{setBusy(false);}}};}
export function Toast({message,error,onClose}:{message:string;error:boolean;onClose:()=>void}){useEffect(()=>{const id=setTimeout(onClose,6000);return()=>clearTimeout(id);},[message,onClose]);return <div className={`toast ${error?'error':''}`} role={error?'alert':'status'}>{error?<AlertCircle size={20}/>:<CheckCircle2 size={20}/>}<span>{message}</span><button aria-label="Close" onClick={onClose}><X size={16}/></button></div>;}
export function TextLink({children,onClick}:{children:ReactNode;onClick:()=>void}){return <button className="text-link" onClick={onClick} type="button">{children}<ArrowRight size={15}/></button>;}
